site_name: StarLib Wiki
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - content.code.copy
    - content.code.annotate
nav:
  - Home: 'index.md'
  - 'Time Utilities': 
    - TimeUnit: 'time/timeunit.md'
    - Duration: 'time/duration.md'
    - TimeParser: 'time/timeparser.md'
    - TimeFormat: 'time/timeformat.md'
  - Numbers: 'helper/numbers.md'
  - Pair: 'pair.md'
  - Value: 'value.md'
  - Reflection:
      - ReflectionHelper: 'reflection/reflectionhelper.md'
      - URLClassLoader: 'reflection/urlclassloaderaccess.md'
  - Tasks: 'tasks.md'
  - Registry: 'registry.md'
  - Converter: 'converter.md'
  - Observable: 'observable.md'
repo_url: 'https://github.com/StarDevelopmentLLC/StarLib'
repo_name: 'StarDevelopmentLLC/StarLib'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences